title: We Are America
subtitle: Voices of the Nation's Future
description: Here's a paragraph about the project and website. I'm adding another sentence to increase the length of this placeholder.

url: https://katmh.com/weareamerica
# all URLs are relative and must begin with a slash

stories_section_title: Hear Our Stories
stories_section_description: Each student in our class has shared a 5-minute, true story from their life. This paragraph will explain what the stories are and their purpose.

contact_section_title: Connect With Us
contact_section_description: Buy our book, let us know about speaking engagements. Fill out the form to reach us if you have any questions or comments.

header_links:
  - title: About
    url: /about
  - title: Instagram
    url: https://instagram.com/lhsweareamerica
  - title: Contact Us
    url: #contact

sass:
  style: compressed

collections:
  stories_data:
    output: true