---
title: We Are America
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  stories_data:
    title: Stories Data
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: Voices of the Nation's Future
brief_description: We Are America is a book by students in Seminar in American Diversity
  at Lowell High School. Through our powerful, personal stories, we represent voices
  of the nation's future and are always looking to share our project with the community.
about_content: We Are America is a book by students in the Seminar in American Diversity
  class at Lowell High School. Through our powerful, personal stories, we represent
  voices of the nation's future and are always looking to share our project with the
  community.
url: https://lhsweareamerica.com
contact_blurb: We'd love to share our experiences and ideas with you. If you're interested
  in getting in touch to buy our book, interview us, or simply chat, fill out this
  form and we'll respond soon.
header_links:
- title: About
  active: true
  id: about-link
- title: Contact
  id: contact-link
- title: Instagram
  id: contact-link
  url: https://instagram.com/lhsweareamerica
sass:
  style: compressed
