---
title: We Are America
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  stories_data:
    title: Stories Data
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: Voices of the Nation's Future
brief_description: We Are America is a book by students in Seminar in American Diversity
  at Lowell High School. Through our powerful, personal stories, we represent voices
  of the nation's future and are always looking to share our project with the community.
about_content: Full description about us, can be multiple paragraphs
url: https://katmh.com/weareamerica
contact_blurb: Buy our book, let us know about speaking engagements. Fill out the
  form to reach us if you have any questions or comments.
header_links:
- title: About
  active: true
  id: about-link
- title: Contact
  id: contact-link
- title: Instagram
  id: contact-link
  url: https://instagram.com/lhsweareamerica
sass:
  style: compressed
plugins:
- jekyll-manager
