title: We Are America
description: A project by the Seminar in American Diversity class at Lowell High School in Massachusetts.

url: https://katmh.com/weareamerica
# all URLs are relative and must begin with a slash

stories_section_title: Hear Our Stories
stories_section_description: Each student in our class has shared a 5-minute, true story from their life. This paragraph will explain what the stories are and their purpose.

contact_section_title: Connect With Us
contact_section_description: Buy our book, let us know about speaking engagements. Fill out the form to reach us if you have any questions or comments.

sass:
  style: compressed

collections:
  stories_data:
    output: true